# Generated by Django 4.2.1 on 2023-05-21 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0011_remove_event_purchase_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_concerts",
                    models.ManyToManyField(
                        related_name="preffered_users_concert", to="events.event"
                    ),
                ),
                (
                    "preffered_movies",
                    models.ManyToManyField(
                        related_name="preffered_user_movie", to="events.event"
                    ),
                ),
                (
                    "preffered_plays",
                    models.ManyToManyField(
                        related_name="preffered_user_play", to="events.event"
                    ),
                ),
                (
                    "unpreferred_concerts",
                    models.ManyToManyField(
                        related_name="unpreffered_users_concert", to="events.event"
                    ),
                ),
                (
                    "unpreffered_lays",
                    models.ManyToManyField(
                        related_name="unpreffered_users_play", to="events.event"
                    ),
                ),
                (
                    "unpreffered_movies",
                    models.ManyToManyField(
                        related_name="unpreffered_user_movie", to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
