# Generated by Django 4.2.1 on 2023-05-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_basepoint_location_remove_city_location_and_more"),
        (
            "recomendations",
            "0002_rename_unpreffered_lays_userpreferences_unpreffered_plays",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NearestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearest_model_rel",
                        to="events.event",
                    ),
                ),
                (
                    "nearest",
                    models.ManyToManyField(
                        related_name="nearest_model_rev_rel", to="events.event"
                    ),
                ),
            ],
        ),
    ]
