# Generated by Django 4.2.1 on 2023-05-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_basepoint_location_remove_city_location_and_more"),
        ("recomendations", "0003_nearestevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearestHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearest_hotel_rel",
                        to="events.hotel",
                    ),
                ),
                (
                    "nearest_events",
                    models.ManyToManyField(
                        related_name="nearest_hotel_rev_rel", to="events.event"
                    ),
                ),
            ],
        ),
    ]
