# Generated by Django 4.2.1 on 2023-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_userroute_baseuserroutepoint_userroutetransaction_and_more"),
        ("recomendations", "0004_nearesthotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="prefferred_attractions",
            field=models.ManyToManyField(
                related_name="preffered_users_attractions", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="prefferred_museums",
            field=models.ManyToManyField(
                related_name="preffered_users_museums", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="unprefferred_attractions",
            field=models.ManyToManyField(
                related_name="unpreffered_users_attractions", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="unprefferred_museums",
            field=models.ManyToManyField(
                related_name="unpreffered_users_museums", to="events.event"
            ),
        ),
    ]
