# Generated by Django 4.2.1 on 2023-05-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_category_pointcategory_delete_tag"),
        ("recomendations", "0006_nearestrestauranttohotel_nearestrestauranttoevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearestEventToRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events", models.ManyToManyField(to="events.event")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.restaurant",
                    ),
                ),
            ],
        ),
    ]
