# Generated by Django 4.2.1 on 2023-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_city_temperature_city_weather_condition"),
        ("recomendations", "0008_userpreferences_preferred_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="prefered_other",
            field=models.ManyToManyField(related_name="other_users", to="events.event"),
        ),
    ]
