# Generated by Django 4.2.1 on 2023-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_city_temperature_city_weather_condition"),
        ("recomendations", "0009_userpreferences_prefered_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="prefered_hotels",
            field=models.ManyToManyField(related_name="hotels_user", to="events.hotel"),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="prefered_restaurants",
            field=models.ManyToManyField(
                related_name="restaurant_user", to="events.restaurant"
            ),
        ),
    ]
