# Generated by Django 4.2.1 on 2023-05-20 09:38

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionMedia",
            fields=[
                (
                    "oid",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("type", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="location",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="location",
        ),
        migrations.AddField(
            model_name="basepoint",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default=0, max_length=63
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("fair", "ярмарка"),
                    ("boulevard", "бульвар"),
                    ("attraction", "достопримечательность"),
                    ("excursion", "экскурсия"),
                    ("theatre", "театр"),
                    ("museum", "музей"),
                    ("movie", "кино"),
                    ("concert", "концерт"),
                    ("plays", "спектакли"),
                ],
                db_index=True,
                default="fair",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="events.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.TextField(default="dd"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="description_short",
            field=models.CharField(default="ewfew", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="description_title",
            field=models.CharField(default="sdf", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="showcase_cards",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="url",
            field=models.URLField(default="f"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Museum",
        ),
        migrations.AddField(
            model_name="regionmedia",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="events.region",
            ),
        ),
    ]
