# Generated by Django 4.2.1 on 2023-05-20 09:59

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_region_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default=0, max_length=63
            ),
            preserve_default=False,
        ),
    ]
