# Generated by Django 4.2.1 on 2023-05-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_city_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="events.region",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="title",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
