# Generated by Django 4.2.1 on 2023-05-20 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_place_region_place_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="phones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="sites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250), null=True, size=None
            ),
        ),
    ]
