# Generated by Django 4.2.1 on 2023-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_place_phones_alter_place_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
