# Generated by Django 4.2.1 on 2023-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_place_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepoint",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pointmedia",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="description_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="region",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="regionmedia",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="oid",
            field=models.CharField(
                max_length=24, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
