# Generated by Django 4.2.1 on 2023-05-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_basepoint_oid_alter_city_oid_alter_place_oid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basepoint",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="basepoint",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="basepoint",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="event",
            name="ya_id",
        ),
        migrations.AddField(
            model_name="basepoint",
            name="can_buy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="basepoint",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="events.place",
            ),
        ),
        migrations.AddField(
            model_name="basepoint",
            name="priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basepoint",
            name="sort",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_method",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="purchase_method",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="age",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Возрастное ограничение",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="discover_moscow_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="description_title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="region",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
