# Generated by Django 4.2.1 on 2023-05-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_remove_basepoint_creator_remove_basepoint_partner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepoint",
            name="parser_source",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
