# Generated by Django 4.2.1 on 2023-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_basepoint_parser_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="purchase_method",
        ),
        migrations.AlterField(
            model_name="event",
            name="payment_method",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
