# Generated by Django 4.2.1 on 2023-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_event_purchase_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
