# Generated by Django 4.2.1 on 2023-05-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_remove_excursionroute_excursion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepoint",
            name="lat",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="basepoint",
            name="lon",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="city",
            name="lat",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="city",
            name="lon",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="lat",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="lon",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
