# Generated by Django 4.2.1 on 2023-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_basepoint_location_remove_city_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="extra_kwargs",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="basepoint",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
