# Generated by Django 4.2.1 on 2023-05-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_userroute_baseuserroutepoint_userroutetransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "oid",
                    models.CharField(
                        max_length=24, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PointCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="events.category",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="events.basepoint",
                    ),
                ),
            ],
            options={
                "unique_together": {("point", "category")},
            },
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
