# Generated by Django 4.2.1 on 2023-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_alter_hotel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="type",
            field=models.CharField(
                choices=[("restaurant", "ресторан"), ("bar", "бар"), ("cafe", "кафе")],
                db_index=True,
                default="restaurant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("fair", "ярмарка"),
                    ("boulevard", "бульвар"),
                    ("attraction", "достопримечательность"),
                    ("excursion", "экскурсия"),
                    ("theatre", "театр"),
                    ("museum", "музей"),
                    ("movie", "кино"),
                    ("concert", "концерт"),
                    ("plays", "спектакли"),
                    ("artwork", "произведение искусства"),
                    ("shop", "торговый центр"),
                    ("gallery", "галерея"),
                    ("theme_park", "тематический парк"),
                    ("viewpoint", "обзорная точка"),
                    ("zoo", "зоопарк"),
                    ("other", "другое"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
