# Generated by Django 4.2.1 on 2023-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_restaurant_extra_kwargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepoint",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
