# Generated by Django 4.2.1 on 2023-05-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_basepoint_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userroute",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userroutepoint",
            name="baseuserroutepoint_ptr",
        ),
        migrations.RemoveField(
            model_name="userroutepoint",
            name="point",
        ),
        migrations.RemoveField(
            model_name="userroutetransaction",
            name="baseuserroutepoint_ptr",
        ),
        migrations.RemoveField(
            model_name="userroutetransaction",
            name="point_from",
        ),
        migrations.RemoveField(
            model_name="userroutetransaction",
            name="point_to",
        ),
        migrations.DeleteModel(
            name="BaseUserRoutePoint",
        ),
        migrations.DeleteModel(
            name="UserRoute",
        ),
        migrations.DeleteModel(
            name="UserRoutePoint",
        ),
        migrations.DeleteModel(
            name="UserRouteTransaction",
        ),
    ]
