# Generated by Django 4.2.1 on 2023-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_baseuserroutedatepoint_userroute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="temperature",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="city",
            name="weather_condition",
            field=models.CharField(default="clear", max_length=250),
        ),
    ]
