# Generated by Django 4.2.1 on 2023-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_city_temperature_city_weather_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="userroute",
            name="description",
            field=models.TextField(default="описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userroute",
            name="title",
            field=models.CharField(default="маршрут", max_length=250),
            preserve_default=False,
        ),
    ]
